# cloudbuild.yaml
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/docker-deploy/pv-bot:$SHORT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/docker-deploy/pv-bot:$SHORT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - gcloud compute instances update-container instance-pv-bot-dev \
        --zone=us-central1-c \
        --container-image=us-central1-docker.pkg.dev/$PROJECT_ID/docker-deploy/pv-bot:$SHORT_SHA
        --container-env="PORT=${_PORT},DISCORD_TOKEN=$$DISCORD_TOKEN, MONGODB_URI=$$MONGODB_URI"
    secretEnv: ["MONGODB_URI", "DISCORD_TOKEN"]

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/bot_token/versions/latest"
      env: "DISCORD_TOKEN"
    - versionName: "projects/$PROJECT_ID/secrets/mongo_uri/versions/latest"
      env: "MONGODB_URI"
