steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/discord-bot:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/discord-bot:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "discord-bot-dev"
      - "--command"
      - >
        "sudo docker pull gcr.io/$PROJECT_ID/discord-bot:$COMMIT_SHA &&
        sudo docker stop discord-container || true &&
        sudo docker rm discord-container || true &&
        sudo docker run -d --name discord-container gcr.io/$PROJECT_ID/discord-bot:$COMMIT_SHA"
