services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo/
      ME_CONFIG_BASICAUTH: false
  bot:
    image: crm-bot
    build: .
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://root:example@mongo/admin
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: package.json
volumes:
  mongo_data:
