name: Bug Report
description: File a bug report.
title: "[request]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: input
    id: contact
    attributes:
      label: Discord Username
      description: How can we get in touch with you if we need more info?
      placeholder: ex. wumpus
    validations:
      required: false
  - type: textarea
    id: desiered-outcome
    attributes:
      label: what would you like to see
      description: Also tell us, your idea
      placeholder: Tell us what you would like to see!
    validations:
      required: true
