# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
    resources:
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: Git
          directives:
              description: Install Git
              allowPrerelease: true
          settings:
              id: Git.Git
              source: winget
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: VSCode
          directives:
              description: Install Visual Studio Code
              allowPrerelease: true
          settings:
              id: Microsoft.VisualStudioCode
              source: winget
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: npm
          directives:
              description: Install Node.JS LTS
              allowPrerelease: true
          settings:
              id: OpenJS.NodeJS.LTS
              source: winget
        - resource: NpmDsc/NpmPackage
          id: yarn
          dependsOn:
              - npm
          directives:
              description: Install Yarn
              allowPrerelease: true
          settings:
              Name: 'yarn'
              Global: true
              PackageDirectory: '${WinGetConfigRoot}\..\'
        - resource: NpmDsc/NpmPackage
          id: typescript
          dependsOn:
              - npm
          directives:
              description: Install Typescript
              allowPrerelease: true
          settings:
              Name: 'typescript'
              Global: true
              PackageDirectory: '${WinGetConfigRoot}\..\'
    configurationVersion: 0.2.0
