import { ActionRowBuilder, ButtonBuilder, ButtonStyle } from "discord.js"

const stackAddQueue = new ButtonBuilder()
		.setStyle(ButtonStyle.Primary)
		.setCustomId('stack_addToQueue')
		.setLabel('Join Queue')
		.setEmoji("➕")
const toggleTimeSensitive = new ButtonBuilder()
		.setStyle(ButtonStyle.Secondary)
		.setCustomId('stack_toggleTimeSensitive')
		.setLabel('Toggle Time Sensitive')
		.setEmoji("⏰")
const removeFromQueue = new ButtonBuilder()
		.setStyle(ButtonStyle.Danger)
		.setCustomId('stack_removeFromQueue')
		.setLabel('Leave Queue')
		.setEmoji("✖️")
const goNext = new ButtonBuilder()
		.setStyle(ButtonStyle.Secondary)
		.setCustomId('stack_goNext')
		.setLabel('Next Speaker')
		.setEmoji("🎙️")
const takeOwner = new ButtonBuilder()
	.setStyle(ButtonStyle.Secondary)
	.setCustomId('stack_ownerTakeOver')
	.setLabel('Take Ownership')
export const row = new ActionRowBuilder<ButtonBuilder>().addComponents(stackAddQueue,toggleTimeSensitive, removeFromQueue, goNext)
export const owner = new ActionRowBuilder<ButtonBuilder>().addComponents(takeOwner)
