# .github/workflows/lint.yml

name: Lint # name of the action (displayed in the github interface)

on: # event list
    pull_request: # on a pull request to each of these branches
        branches: [main]
    push:
        branches: [main]

jobs: # list of things to do
    linting:
        name: Linting # job name (unique id)
        runs-on: ubuntu-latest # on which machine to run

        strategy:
            matrix:
                NODE_VERSION: [18.x, 20.x]

        steps: # list of steps
            - name: Install NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.NODE_VERSION }}

            - name: Code Checkout
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: yarn install --frozen-lockfile --silent
              env:
                  CI: true

            - name: Lint with Yarn
              run: yarn lint
